Disable obsolete use_2to3 option; run 2to3 manually
Note: Without the `use_2to3` option available anymore, the unit test
loading fails with:

Traceback (most recent call last):
  File "/builddir/build/BUILD/nose-1.3.7/setup.py", line 78, in <module>
    setup(
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/site-packages/setuptools/command/test.py", line 223, in run
    self.run_tests()
  File "/usr/lib/python3.9/site-packages/setuptools/command/test.py", line 226, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.9/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.9/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.9/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.9/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.9/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.9/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.9/site-packages/setuptools/command/test.py", line 56, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.9/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.9/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(TestLoader.loadTestsFromModule(self, module))
  File "/usr/lib/python3.9/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/usr/lib/python3.9/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/usr/lib/python3.9/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib/python3.9/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "/builddir/build/BUILD/nose-1.3.7/nose/case.py", line 30, in __init__
    raise TypeError("nose.case.Test called with argument %r that "
TypeError: nose.case.Test called with argument 'runTest' that is not callable. A callable is required.

I suspect it's related to this code block being removed:

https://github.com/pypa/setuptools/commit/ca296ca866#diff-0b755809db0a62c7f9085371b630e186cbf8455d05c2aacbdd45b7f0fc4026d0L235

Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>